/**
* pepper.js is just an added security measure for password hashing.
* The pepper is a cryptographicaly secure random generated number that
* is stored on a separate server than the salt so that if the database is
* compromised, attackers wouldn't be able to recreate the hashing mecanism.
* The pepper is static from user to user.
* When hashing the password, the hashing funtion does the following :
* OneWayHashFunction(password + (salt + pepper)).
* Pepper is generated by 
*/

exports.getPepper = function() {
	return '3ee28a71618d4a9520a5f5ab6253794d2156e287413df6ad40bb6d46628025b582b0db135e89eebb13b7b386d886fa378bdacdc548361a62d5bb285e163087303bde9dced2597afc89cacc6fe3f44766392b3c412cf9589a9be4c92d52192ebec34c62aab1e3e653b255c8aafb04a3314719184e626f51b2fe8a94c4da09198cae1d81aad7cfb7ee434e47c610ddf358783a05b5c00651604d0766403c69ab67c92852150607953598d110702606f522d0af2eea9c298b58e5f0efbe61ca9e870a701464c1260b97a381134dea2fd2e4a27e22efe633e44f8b94657af4eea7b0570afeae5c994377e5f7f0647a9092417ba7f1c066645f56ee4170b225a4d43c';
};